//
//  InjectionLiteC.h
//
//  Created by John Holdsworth on 13/03/2023.
//
#if DEBUG || !SWIFT_PACKAGE
#import <Foundation/Foundation.h>
#define APP_NAME "InjectionLite"
#define APP_PREFIX "🔥 "
#define VAPOR_SYMBOL "$s10RoutingKit10ParametersVN"
#define TCA_SYMBOL "_$s22ComposableArchitecture6LoggerCN"

// Environment variables that can be used in schemes.
#define INJECTION_DIRECTORIES "INJECTION_DIRECTORIES"
#define INJECTION_PROJECT_ROOT "BUILD_WORKSPACE_DIRECTORY"
#define INJECTION_SWEEP_DETAIL "INJECTION_SWEEP_DETAIL"
#define INJECTION_SWEEP_EXCLUDE "INJECTION_SWEEP_EXCLUDE"
#define INJECTION_STANDALONE_INHIBIT "INJECTION_STANDALONE_INHIBIT"
#define INJECTION_OF_GENERICS "INJECTION_OF_GENERICS"
#define INJECTION_NOGENERICS "INJECTION_NOGENERICS"
#define INJECTION_NOKEYPATHS "INJECTION_NOKEYPATHS"
#define INJECTION_KEYPATHS "INJECTION_KEYPATHS"
#define INJECTION_DETAIL "INJECTION_DETAIL"
#define INJECTION_BENCH "INJECTION_BENCH"
#define INJECTION_HOST "INJECTION_HOST"

@interface NSObject(InjectionBoot)
+ (BOOL)InjectionBoot_inPreview;
+ (void)runXCTestCase:(Class)aTestCase;
@end
#endif
